name: Generate Podcast Feeds
on: [push]
jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: kovalchukum/podcast-generator@main
